FROM rust:1.48.0-buster

RUN apt update && apt install -y gcc libprotobuf-dev wait-for-it
WORKDIR /usr/src/celo-light-client
COPY Cargo.toml .
COPY Cargo.lock .
COPY src src
COPY examples examples

RUN cargo build --example lightest-sync --release

RUN cp target/release/examples/lightest-sync /usr/local/bin/lightest-sync
RUN chmod +x /usr/local/bin/lightest-sync

CMD ["RUST_LOG=info", "lightest-sync", "--fast"]
