version: '3.4'
services:
  geth:
    image: us.gcr.io/celo-org/geth:mainnet
    entrypoint: sh /run_geth_in_docker.sh --maxpeers 50 --light.maxpeers 20 --syncmode lightest --rpc --rpcaddr 0.0.0.0 --ws --wsaddr 0.0.0.0 --wsport 3334 --wsapi eth,net,web3 --rpccorsdomain '*'
    ports:
       - 3334:3334
       - 8545:8545
    networks:
      common:
        ipv4_address: 172.20.0.4
    logging:
        driver: none

  light-client-example:
    image: light-client-example
    build:
      context: .
      dockerfile: Dockerfile.example
    depends_on:
      - "geth"
    links:
      - "geth"
    environment:
      - RUST_LOG=info
    # ensure the geth is up and running
    command: sh -c "sleep 5; wait-for-it 172.20.0.4:8545 -t 15 -- lightest-sync --fast --addr 'http://172.20.0.4:8545'"
    networks:
      common:
        ipv4_address: 172.20.0.5

networks:
  common:
    ipam:
      config:
        - subnet: 172.20.0.0/24
